/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }
    
   
    
    //validation
    public boolean ValidateLogin(){
        String name = username.getText();
        String pass = password.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "please enter username");
            return false;
        }
        if(pass.equals("")){
            JOptionPane.showMessageDialog(this, "please enter password");
            return false;
        }
        
        return true;
    }
    
    //verify creds
    public void login(){
      String name = username.getText();
      String pass = password.getText();
        
      try{
          Connection con = DBConnection.getConnection();
          
          PreparedStatement pst = con.prepareStatement("select * from users where name = ? and password = ?");
          
          pst.setString(1, name);
          pst.setString(2, pass);
          
          ResultSet rs = pst.executeQuery();
          if(rs.next()){
              JOptionPane.showMessageDialog(this, "Login successful");
              HomePage home = new HomePage();
              home.setVisible(true);
              this.dispose();
          }else{
              JOptionPane.showMessageDialog(this, "incorrect username or password");
          }
          
      } catch(Exception e){
          e.printStackTrace();
      }
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Readme1 = new javax.swing.JLabel();
        Readme4 = new javax.swing.JLabel();
        Readme3 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Readme5 = new javax.swing.JLabel();
        Readme6 = new javax.swing.JLabel();
        Readme7 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        Readme9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Readme10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Readme1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Readme1.setForeground(new java.awt.Color(255, 255, 255));
        Readme1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme1.setText("ReadMe");
        jPanel1.add(Readme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        Readme4.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        Readme4.setForeground(new java.awt.Color(255, 255, 255));
        Readme4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme4.setText("ReadMe");
        Readme4.setFocusable(false);
        Readme4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Readme4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 260, -1));

        Readme3.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        Readme3.setForeground(new java.awt.Color(255, 255, 255));
        Readme3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme3.setText("Welcome to ");
        jPanel1.add(Readme3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 230, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/library.jpg"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 840));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Readme5.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        Readme5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme5.setText("X");
        Readme5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Readme5MouseClicked(evt);
            }
        });
        jPanel2.add(Readme5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 20, -1));

        Readme6.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        Readme6.setForeground(new java.awt.Color(153, 102, 0));
        Readme6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme6.setText("Login to your existing account");
        jPanel2.add(Readme6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 260, -1));

        Readme7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Readme7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme7.setText("Username");
        jPanel2.add(Readme7, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 200, 90, -1));

        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 450, 40));

        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 450, 40));

        Readme9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Readme9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme9.setText("Password");
        jPanel2.add(Readme9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 90, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 140, 50));

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 51), 1, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setLabel("Sign up");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 140, 50));

        Readme10.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Readme10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme10.setText("Login Page");
        jPanel2.add(Readme10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 1620, 830));

        setSize(new java.awt.Dimension(1623, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(ValidateLogin()){
            login();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Readme5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Readme5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_Readme5MouseClicked

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        
    }//GEN-LAST:event_usernameFocusLost

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Signup page = new Signup();
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Readme1;
    private javax.swing.JLabel Readme10;
    private javax.swing.JLabel Readme3;
    private javax.swing.JLabel Readme4;
    private javax.swing.JLabel Readme5;
    private javax.swing.JLabel Readme6;
    private javax.swing.JLabel Readme7;
    private javax.swing.JLabel Readme9;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
