/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import java.sql.Connection;

/**
 *
 * @author Dell
 */
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    //to fetch the issue book  from the database and display it to panel
    public void getIssuedBook(){
        int bookId = Integer.parseInt(issuebId.getText());
        int studentId = Integer.parseInt(issuesId.getText());
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "select * from issuebook where book_id = ? and student_id = ? and status = ?";
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, bookId);
            pst.setInt(2, studentId);
            pst.setString(3, "Pending");
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                issueId_lbl.setText(rs.getString("id"));
                bookName_lbl.setText(rs.getString("book_name"));
                studentName_lbl.setText(rs.getString("student_name"));
                issueDate_lbl.setText(rs.getString("issue_date"));
                dueDate_lbl.setText(rs.getString("due_date"));
                bookError.setText("");
                
            }else{
                bookError.setText("No Record Found");
                
                issueId_lbl.setText("");
                bookName_lbl.setText("");
                studentName_lbl.setText("");
                issueDate_lbl.setText("");
                dueDate_lbl.setText("");
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //return the book
    public boolean returnBook(){
        boolean isReturned = false;
        int bookId = Integer.parseInt(issuebId.getText());
        int studentId = Integer.parseInt(issuesId.getText());
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "update issuebook set status = ? where student_id = ? and book_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, "Returned");
            pst.setInt(2, studentId);
            pst.setInt(3, bookId);
            pst.setString(4, "Pending");
            
            int rowCount = pst.executeUpdate();
            
            if(rowCount > 0){
                isReturned = true;
                
            }else{
                isReturned = false;
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return isReturned;
    }
    
    //Updating counts of books after issued
    public void updateBookCount(){
        int bookId = Integer.parseInt(issuebId.getText());
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "update book_details set quantity = quantity + 1 where book_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, bookId);
            
            int rowCount = pst.executeUpdate();
            
            if(rowCount > 0){
                JOptionPane.showMessageDialog(this, "Book Count Updated");
                
                
            }else{
                JOptionPane.showMessageDialog(this, "Book Count Can't Be Updated");
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bookError_lbl = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        issueId_lbl = new javax.swing.JLabel();
        studentName_lbl = new javax.swing.JLabel();
        bookName_lbl = new javax.swing.JLabel();
        bookError = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        issueDate_lbl = new javax.swing.JLabel();
        dueDate_lbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        issuesId = new javax.swing.JTextField();
        issuebId = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        Readme5 = new javax.swing.JLabel();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1450, 970));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("<< Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Book Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 250, 3));

        bookError_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookError_lbl.setForeground(new java.awt.Color(255, 255, 102));
        jPanel2.add(bookError_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 290, 30));

        jLabel26.setBackground(new java.awt.Color(255, 204, 153));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Issue Id:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 70, -1));

        jLabel27.setBackground(new java.awt.Color(255, 204, 153));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Book Name:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 90, -1));

        jLabel28.setBackground(new java.awt.Color(255, 204, 153));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Student Name:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 100, -1));
        jPanel2.add(issueId_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 210, 30));
        jPanel2.add(studentName_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 210, 30));
        jPanel2.add(bookName_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 210, 30));
        jPanel2.add(bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 210, 30));

        jLabel36.setBackground(new java.awt.Color(255, 204, 153));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setText("Due Date:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 80, -1));

        jLabel37.setBackground(new java.awt.Color(255, 204, 153));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setText("Issue Date:");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 80, -1));
        jPanel2.add(issueDate_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 210, 30));
        jPanel2.add(dueDate_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 210, 30));

        panel_main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 828));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Return Book:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 204, 153));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("Book Id:");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 250, 3));

        jLabel35.setBackground(new java.awt.Color(102, 102, 0));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setText("Student Id:");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 120, -1));

        issuesId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));
        issuesId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                issuesIdFocusLost(evt);
            }
        });
        issuesId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuesIdActionPerformed(evt);
            }
        });
        jPanel5.add(issuesId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 360, 30));

        issuebId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));
        issuebId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                issuebIdFocusLost(evt);
            }
        });
        issuebId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebIdActionPerformed(evt);
            }
        });
        jPanel5.add(issuebId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 360, 30));

        button1.setBackground(new java.awt.Color(255, 204, 51));
        button1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Find Book");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel5.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 200, 50));
        button1.getAccessibleContext().setAccessibleName("Return Book");

        Readme5.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        Readme5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme5.setText("X");
        Readme5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Readme5MouseClicked(evt);
            }
        });
        jPanel5.add(Readme5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 20, -1));

        button2.setBackground(new java.awt.Color(204, 0, 0));
        button2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("Return Book");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel5.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 200, 50));

        panel_main.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 800, 830));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 828));

        setSize(new java.awt.Dimension(1620, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void issuesIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuesIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuesIdActionPerformed

    private void issuebIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuebIdActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        getIssuedBook();
    }//GEN-LAST:event_button1ActionPerformed

    private void Readme5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Readme5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_Readme5MouseClicked

    private void issuebIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issuebIdFocusLost
        if(!issuebId.getText().equals("")){
;
        }
        
    }//GEN-LAST:event_issuebIdFocusLost

    private void issuesIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_issuesIdFocusLost
        if(!issuesId.getText().equals("")){

        }
        
    }//GEN-LAST:event_issuesIdFocusLost

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        if(returnBook() == true){
            JOptionPane.showMessageDialog(this, "Book Returned Successfully");
            updateBookCount();
        }else{
           JOptionPane.showMessageDialog(this, "Book Isn't Returned"); 
        }
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Readme5;
    private javax.swing.JLabel bookError;
    private javax.swing.JLabel bookError_lbl;
    private javax.swing.JLabel bookName_lbl;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel dueDate_lbl;
    private javax.swing.JLabel issueDate_lbl;
    private javax.swing.JLabel issueId_lbl;
    private javax.swing.JTextField issuebId;
    private javax.swing.JTextField issuesId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panel_main;
    private javax.swing.JLabel studentName_lbl;
    // End of variables declaration//GEN-END:variables
}
