/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author Dell
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }
    
    //method to insert values to users table
    public void insertSignupDetails(){
        String name = username.getText();
        String mail = email.getText();
        String pass = password.getText();
        String ct = contact.getText();
        
        try{
           Connection con = DBConnection.getConnection();
           String sql = "insert into users(name, email, password, contact) values(?,?,?,?)";
           PreparedStatement pst = con.prepareStatement(sql);

           pst.setString(1, name);
           pst.setString(2, mail);
           pst.setString(3, pass);
           pst.setString(4, ct);
           
           int updatedRowCount = pst.executeUpdate();
           
           if(updatedRowCount > 0){
               JOptionPane.showMessageDialog(this, "Recorded Inserted Successfully");
               Login page = new Login();
               page.setVisible(true);
               dispose();
           }else{
               JOptionPane.showMessageDialog(this, "Recorded Insertion Failure");               
           }

        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    //validation
    
    public boolean validateSignup(){
        String name = username.getText();
        String pass = password.getText();
        String mail = email.getText();
        String ct = contact.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "please enter username");
            return false;
        }
        if(pass.equals("")){
            JOptionPane.showMessageDialog(this, "please enter password");
            return false;
        }
        if(mail.equals("") || !mail.matches("^.+@.+\\..+$")){
            JOptionPane.showMessageDialog(this, "please enter a valid email");
            return false;
        }
        if(ct.equals("")){
            JOptionPane.showMessageDialog(this, "please enter contact number");
            return false;
        }
        return true;
    }
    
    //check duplicate users
    public boolean checkDuplicateUser(){
        String name = username.getText();
        boolean isExist = false;
        
        try{
            Connection con = DBConnection.getConnection();
            
            PreparedStatement pst = con.prepareStatement("select * from users where name = ?");
            pst.setString(1, name);
            pst.executeQuery();
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExist = true;
            }else{
                isExist = false;
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return isExist;
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Readme1 = new javax.swing.JLabel();
        Readme4 = new javax.swing.JLabel();
        Readme3 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Readme = new javax.swing.JLabel();
        Readme5 = new javax.swing.JLabel();
        Readme6 = new javax.swing.JLabel();
        Readme7 = new javax.swing.JLabel();
        Readme8 = new javax.swing.JLabel();
        Readme9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Readme10 = new javax.swing.JLabel();
        password = new app.bolivia.swing.JCTextField();
        username = new app.bolivia.swing.JCTextField();
        email = new app.bolivia.swing.JCTextField();
        contact = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1620, 840));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Readme1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Readme1.setForeground(new java.awt.Color(255, 255, 255));
        Readme1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme1.setText("ReadMe");
        jPanel1.add(Readme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        Readme4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        Readme4.setForeground(new java.awt.Color(255, 255, 255));
        Readme4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme4.setText("ReadMe");
        Readme4.setFocusable(false);
        Readme4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Readme4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 260, -1));

        Readme3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        Readme3.setForeground(new java.awt.Color(255, 255, 255));
        Readme3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme3.setText("Welcome to ");
        jPanel1.add(Readme3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 230, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/library.jpg"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 840));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Readme.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Readme.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme.setText("Contact");
        jPanel2.add(Readme, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 70, -1));

        Readme5.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        Readme5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme5.setText("X");
        Readme5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Readme5MouseClicked(evt);
            }
        });
        jPanel2.add(Readme5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 20, -1));

        Readme6.setFont(new java.awt.Font("Corbel Light", 0, 20)); // NOI18N
        Readme6.setForeground(new java.awt.Color(153, 102, 0));
        Readme6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme6.setText("Create New Account");
        jPanel2.add(Readme6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 170, -1));

        Readme7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Readme7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme7.setText("Username");
        jPanel2.add(Readme7, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 200, 90, -1));

        Readme8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Readme8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme8.setText("Email");
        jPanel2.add(Readme8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 50, -1));

        Readme9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        Readme9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme9.setText("Password");
        jPanel2.add(Readme9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 90, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 140, 50));

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 51), 1, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setLabel("Sign up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 140, 50));

        Readme10.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Readme10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Readme10.setText("Signup Page");
        jPanel2.add(Readme10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 150, -1));

        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        password.setForeground(new java.awt.Color(51, 51, 51));
        password.setPlaceholder("Enter your password");
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 450, 40));

        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        username.setForeground(new java.awt.Color(51, 51, 51));
        username.setPlaceholder("Enter your username");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 450, 40));

        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        email.setForeground(new java.awt.Color(51, 51, 51));
        email.setPlaceholder("Enter your email");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 450, 40));

        contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        contact.setForeground(new java.awt.Color(51, 51, 51));
        contact.setPlaceholder("Enter your contact no.");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 450, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 790, 830));

        setSize(new java.awt.Dimension(1623, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(validateSignup() == true){
            if(checkDuplicateUser() == false){
                insertSignupDetails();
            }else{
                JOptionPane.showMessageDialog(this,"username already exist");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Readme5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Readme5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_Readme5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Login page = new Login();
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Readme;
    private javax.swing.JLabel Readme1;
    private javax.swing.JLabel Readme10;
    private javax.swing.JLabel Readme3;
    private javax.swing.JLabel Readme4;
    private javax.swing.JLabel Readme5;
    private javax.swing.JLabel Readme6;
    private javax.swing.JLabel Readme7;
    private javax.swing.JLabel Readme8;
    private javax.swing.JLabel Readme9;
    private app.bolivia.swing.JCTextField contact;
    private app.bolivia.swing.JCTextField email;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private app.bolivia.swing.JCTextField password;
    private app.bolivia.swing.JCTextField username;
    // End of variables declaration//GEN-END:variables
}
